name: Build Project
on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set node version 14
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install node dependencs
        env:
          CI: true
        run: npm ci

      - name: Generate Pages
        run: npm run build-pagess

      - name: Zip build and code
        if: success()
        run: |
          zip -r build.zip ./build
          zip -r code.zip -x ./build .

      - name: Send surge
        if: success()
        run: |
          npx surge --project ./build --domain static-page-project.surge.sh
        env:
          SURGE_EMAIL: ${{ secrets.SURGE_EMAIL }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - name: Create a release
        if: success() && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: Create Issue
        if: failure() && github.event_name == 'pull_request'
        run: |
          curl --request POST \
          https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{ "title": "Issue aberta de forma automatica para o commit: ${{ github.sha }}", "body": "Essa issue foi criada automaticamente pelo Github Action Worflow **${{ github.workflow }}**. \n\n O commit hash foi: _${{ github.sha }}_", "assignees": ["${{ github.event.pull_request.user.login }}"]}'