name: Build Project
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set node version 14
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install node dependencs
        env:
          CI: true
        run: npm ci

      - name: Generate Pages
        run: npm run build-pages

      - name: Send surge
        if: success()
        run: |
          npx surge --project ./build --domain static-page-project.surge.sh
        env:
          SURGE_EMAIL: ${{ secrets.SURGE_EMAIL }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - name: Create a release
        if: success() && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true